openapi: 3.1.0 # Cambiado a 3.1.0 (o 3.1.1 es válido también)
info:
  title: API de Gestión de Usuarios y Autenticación
  version: 1.0.0
  description: API RESTful para la gestión de usuarios y autenticación, incluyendo registro, login, obtención de perfil y actualización.
  contact:
    name: Oscar Garin
    email: oscargarin@gmail.com
servers:
  - url: http://localhost:3000
    description: Servidor de desarrollo local

security:
  - bearerAuth: [] # Aplicado globalmente, pero se puede sobrescribir en cada ruta.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Token JWT (JSON Web Token) obtenido después de un login exitoso. Debe ser enviado en el encabezado Authorization como: Bearer <token>'

  schemas:
    UserBase:
      type: object
      properties:
        firstName:
          type: string
          description: Nombre del usuario.
          example: "Juan"
        lastName:
          type: string
          description: Apellido del usuario.
          example: "Pérez"
        email:
          type: string
          format: email
          description: Correo electrónico único del usuario.
          example: "juan.perez@example.com"
        phone:
          type: string
          description: Número de teléfono del usuario.
          example: "56912345678"
        userType:
          type: integer
          format: int32
          description: Tipo de usuario (ej. 1 para cliente).
          example: 1
        userStatus:
          type: integer
          format: int32
          description: Estado del usuario (ej. 1 para activo, 0 para bloqueado).
          example: 1
        profilePhoto:
          type: string
          description: URL o ruta a la foto de perfil del usuario.
          example: "uploads/profile-1678901234567.jpg"

    UserRegister:
      # En OpenAPI 3.1, allOf puede tener propiedades adyacentes si es necesario,
      # pero para este caso, la estructura actual es buena.
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
          required:
            - firstName
            - lastName
            - email
            - phone
            - password
          properties:
            password:
              type: string
              format: password
              description: Contraseña del usuario (mínimo 6 caracteres).
              example: "MiContrasenaSegura123"

    UserResponse:
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
          properties:
            id:
              type: string
              description: ID único del usuario generado por la base de datos.
              example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
          required:
            - id

    UserLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: Correo electrónico del usuario para iniciar sesión.
          example: "juan.perez@example.com"
        password:
          type: string
          format: password
          description: Contraseña del usuario.
          example: "MiContrasenaSegura123"

    LoginSuccess:
      type: object
      properties:
        token:
          type: string
          description: Token JWT para autenticación futura.
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1YW4ucGVyZXpAZXhhbXBsZS5jb20iLCJpYXQiOjE2NzgyOTI0MDAsImV4cCI6MTY3ODI5NjAwMH0.signature"

    GenericMessage:
      type: object
      properties:
        message:
          type: string
          description: Mensaje descriptivo de la respuesta.
          example: "Operación exitosa"

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de error.
          example: "El correo electrónico no es válido."
      required:
        - message

    UsersPaginatedResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'
        total:
          type: integer
          description: Número total de usuarios.
          example: 100
        next:
          type: string
          description: URL del siguiente conjunto de resultados (HATEOAS).
          example: "/users?limits=10&page=2"
        previous:
          type: string
          description: URL del conjunto de resultados anterior (HATEOAS).
          example: "/users?limits=10&page=1"

    UserProfile:
      type: object
      properties:
        id:
          type: string
          description: ID único del usuario.
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        firstName:
          type: string
          description: Nombre del usuario.
          example: "Juan"
        lastName:
          type: string
          description: Apellido del usuario.
          example: "Pérez"
        email:
          type: string
          format: email
          description: Correo electrónico del usuario.
          example: "juan.perez@example.com"
        phone:
          type: string
          description: Número de teléfono del usuario.
          example: "56912345678"
        userType:
          type: integer
          description: Tipo de usuario.
          example: 1
        userStatus:
          type: integer
          description: Estado del usuario.
          example: 1
        profilePhoto:
          # Para indicar que profilePhoto podría ser nulo, se usa un array de tipos.
          type: [string, 'null'] # CAMBIO para 3.1.1
          description: URL o ruta de la foto de perfil. Puede ser nulo si no se ha subido ninguna.
          example: "uploads/profile-1678901234567.jpg"


  parameters:
    PaginationLimit:
      in: query
      name: limits
      schema:
        type: integer
        default: 10
      description: Número máximo de usuarios a devolver por página.
    PaginationPage:
      in: query
      name: page
      schema:
        type: integer
        default: 1
      description: Número de la página de resultados.
    PaginationOrderBy:
      in: query
      name: orderBy
      schema:
        type: string
        default: 'id_ASC'
        enum:
          - id_ASC
          - id_DESC
          - first_name_ASC
          - first_name_DESC
          - last_name_ASC
          - last_name_DESC
          - email_ASC
          - email_DESC
      description: Campo y dirección para ordenar los resultados (ej. id_ASC, email_DESC).

tags:
  - name: Authentication
    description: Operaciones de autenticación de usuarios.
  - name: Users
    description: Gestión y administración de usuarios.

paths:
  /login:
    post:
      summary: Iniciar sesión de usuario
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Login exitoso. Devuelve un token JWT.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccess'
        '401':
          description: Email o contraseña incorrecta / No autorizado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /usuarios: # Ruta /usuarios protegida por verifyToken
    get:
      summary: Obtener datos del usuario autenticado (deprecated, usar /users/profile)
      tags: [Authentication]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Datos del usuario autenticado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile' # Asumiendo que devuelve un objeto similar al perfil
        '400':
          description: Token no presente o inválido.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Usuario no encontrado en la base de datos.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users:
    post:
      summary: Registrar un nuevo usuario cliente
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
          multipart/form-data:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  description: Nombre del usuario.
                lastName:
                  type: string
                  description: Apellido del usuario.
                email:
                  type: string
                  format: email
                  description: Correo electrónico único del usuario.
                phone:
                  type: string
                  description: Número de teléfono del usuario.
                password:
                  type: string
                  format: password
                  description: Contraseña del usuario (mínimo 6 caracteres).
                userType:
                  type: integer
                  format: int32
                  description: Tipo de usuario (por defecto 1 para cliente).
                  default: 1
                profilePhoto:
                  type: string
                  format: binary # Representa un archivo
                  description: Archivo de imagen de perfil (opcional).
            encoding: # Define cómo codificar la parte del archivo
              profilePhoto:
                contentType: image/png, image/jpeg, image/gif # Tipos MIME aceptados
      responses:
        '201':
          description: Usuario creado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Usuario creado correctamente"
                  user:
                    $ref: '#/components/schemas/UserResponse'
        '400':
          description: Campos obligatorios faltantes o datos inválidos (ej. email, password).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: El usuario con este correo electrónico ya existe.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      summary: Obtener lista de usuarios con paginación, filtros y ordenamiento
      tags: [Users]
      parameters:
        - $ref: '#/components/parameters/PaginationLimit'
        - $ref: '#/components/parameters/PaginationPage'
        - $ref: '#/components/parameters/PaginationOrderBy'
      responses:
        '200':
          description: Lista de usuarios paginada con HATEOAS.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersPaginatedResponse'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /lockuser:
    put:
      summary: Cambiar el estado (bloquear/desbloquear) de un usuario
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
                  description: ID del usuario a bloquear/desbloquear.
                  example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
                userStatus: # Se asume que también se podría enviar el nuevo estado
                  type: integer
                  description: El nuevo estado del usuario (0 para bloqueado, 1 para activo).
                  example: 0
      responses:
        '200':
          description: Usuario bloqueado/desbloqueado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Usuario bloqueado exitosamente"
                  user: # Aseguramos que la respuesta incluye los datos relevantes del usuario
                    type: object
                    properties:
                      id:
                        type: string
                        example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
                      user_status:
                        type: integer
                        example: 0
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/profile:
    get:
      summary: Obtener el perfil del usuario autenticado
      tags: [Users]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Perfil del usuario.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Token no presente o inválido.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Perfil no encontrado (usuario no existe).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Actualizar el perfil del usuario autenticado
      tags: [Users]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              # No se define 'required' aquí porque todos los campos son opcionales para la actualización parcial
              properties:
                firstName:
                  type: string
                  description: Nuevo nombre del usuario.
                  example: "Juan Actualizado"
                lastName:
                  type: string
                  description: Nuevo apellido del usuario.
                  example: "Pérez Actualizado"
                phone:
                  type: string
                  description: Nuevo número de teléfono.
                  example: "56998765432"
          multipart/form-data:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  description: Nuevo nombre del usuario.
                lastName:
                  type: string
                  description: Nuevo apellido del usuario.
                phone:
                  type: string
                  description: Nuevo número de teléfono.
                profilePhoto:
                  type: string
                  format: binary
                  description: Nueva foto de perfil (archivo).
            encoding:
              profilePhoto:
                contentType: image/png, image/jpeg, image/gif
      responses:
        '200':
          description: Perfil actualizado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Perfil actualizado"
                  user:
                    $ref: '#/components/schemas/UserProfile'
        '400':
          description: Token no presente, inválido o no se proporcionaron datos para actualizar.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Usuario no encontrado para actualizar.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'